apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: default
  labels:
    app.kubernetes.io/instance: demo-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    app: demo-app
  type: NodePort
